# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    build_app(scheme: 'BarberStop', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['dawsonpe1820@gmail.com', 'creightontaylor@gmail.com','ledaws09@gmail.com', 'bdawson.lpr@gmail.com', 'lprdawson@gmail.com', 'rcdawson@ucdavis.edu'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '1a802034089ce3c1eb5f48e3ea7700fbc8090bf1',
             build_secret: 'cb3caa7b3f865411f6e4eaf57844fe9e6f6d773987b5135167ca2cdfacd5767e',
                   emails: emails,
                   groups: groups,
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    slack(
      slack_url: "https://hooks.slack.com/services/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",
      channel: "beta-releases",
      message: "@channel Successfully uploaded a beta release - see it at <https://fabric.io/_/beta |beta>"
    )
  end
end

